// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-F5GUMCOYZA9DTWunOcxsafc65V99dI',
    appId: '1:196535392716:web:7e03d9cbece05a4e2e2569',
    messagingSenderId: '196535392716',
    projectId: 'carona-utfpr-efdd9',
    authDomain: 'carona-utfpr-efdd9.firebaseapp.com',
    storageBucket: 'carona-utfpr-efdd9.appspot.com',
    measurementId: 'G-DSV0RYWECC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8TIHSon-ITPUIyBKK5hkNJ-gL56TyCU',
    appId: '1:196535392716:android:da30c059cb36b0352e2569',
    messagingSenderId: '196535392716',
    projectId: 'carona-utfpr-efdd9',
    storageBucket: 'carona-utfpr-efdd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZe9hXRgCvJ_PuEKh_flRxdwj0k2SG8s',
    appId: '1:196535392716:ios:40b5e395479486652e2569',
    messagingSenderId: '196535392716',
    projectId: 'carona-utfpr-efdd9',
    storageBucket: 'carona-utfpr-efdd9.appspot.com',
    iosClientId: '196535392716-fkoq5n02b24mevrr4dpannnbk56vahtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.carona',
  );
}
